// flow-typed signature: d82709f914e652a8784040395db9fb6c
// flow-typed version: <<STUB>>/7zip-bin_v3.1.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '7zip-bin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '7zip-bin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '7zip-bin/index' {
  declare module.exports: $Exports<'7zip-bin'>;
}
declare module '7zip-bin/index.js' {
  declare module.exports: $Exports<'7zip-bin'>;
}
