// flow-typed signature: 9c19921fb7b39f6472dec697963dc71b
// flow-typed version: <<STUB>>/electron-unhandled_v1.1.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-unhandled'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-unhandled' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'electron-unhandled/index' {
  declare module.exports: $Exports<'electron-unhandled'>;
}
declare module 'electron-unhandled/index.js' {
  declare module.exports: $Exports<'electron-unhandled'>;
}
