// flow-typed signature: 3c7c85951609cfa3b607adb4af40b006
// flow-typed version: <<STUB>>/jimp_v0.2.28/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jimp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jimp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jimp/browser/examples/jimp-worker' {
  declare module.exports: any;
}

declare module 'jimp/browser/lib/jimp' {
  declare module.exports: any;
}

declare module 'jimp/browser/lib/jimp.min' {
  declare module.exports: any;
}

declare module 'jimp/browser/src/jimp-wrapper' {
  declare module.exports: any;
}

declare module 'jimp/example' {
  declare module.exports: any;
}

declare module 'jimp/omggif' {
  declare module.exports: any;
}

declare module 'jimp/phash' {
  declare module.exports: any;
}

declare module 'jimp/resize' {
  declare module.exports: any;
}

declare module 'jimp/resize2' {
  declare module.exports: any;
}

declare module 'jimp/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jimp/browser/examples/jimp-worker.js' {
  declare module.exports: $Exports<'jimp/browser/examples/jimp-worker'>;
}
declare module 'jimp/browser/lib/jimp.js' {
  declare module.exports: $Exports<'jimp/browser/lib/jimp'>;
}
declare module 'jimp/browser/lib/jimp.min.js' {
  declare module.exports: $Exports<'jimp/browser/lib/jimp.min'>;
}
declare module 'jimp/browser/src/jimp-wrapper.js' {
  declare module.exports: $Exports<'jimp/browser/src/jimp-wrapper'>;
}
declare module 'jimp/example.js' {
  declare module.exports: $Exports<'jimp/example'>;
}
declare module 'jimp/index' {
  declare module.exports: $Exports<'jimp'>;
}
declare module 'jimp/index.js' {
  declare module.exports: $Exports<'jimp'>;
}
declare module 'jimp/omggif.js' {
  declare module.exports: $Exports<'jimp/omggif'>;
}
declare module 'jimp/phash.js' {
  declare module.exports: $Exports<'jimp/phash'>;
}
declare module 'jimp/resize.js' {
  declare module.exports: $Exports<'jimp/resize'>;
}
declare module 'jimp/resize2.js' {
  declare module.exports: $Exports<'jimp/resize2'>;
}
declare module 'jimp/server.js' {
  declare module.exports: $Exports<'jimp/server'>;
}
