// flow-typed signature: 1ee3c712c5daed72bf4273ee35432812
// flow-typed version: <<STUB>>/osenv_v0.1.4/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'osenv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'osenv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'osenv/osenv' {
  declare module.exports: any;
}

declare module 'osenv/test/unix' {
  declare module.exports: any;
}

declare module 'osenv/test/windows' {
  declare module.exports: any;
}

// Filename aliases
declare module 'osenv/osenv.js' {
  declare module.exports: $Exports<'osenv/osenv'>;
}
declare module 'osenv/test/unix.js' {
  declare module.exports: $Exports<'osenv/test/unix'>;
}
declare module 'osenv/test/windows.js' {
  declare module.exports: $Exports<'osenv/test/windows'>;
}
