// flow-typed signature: 4f4de8e95e9cabf56cf36d14421621ff
// flow-typed version: <<STUB>>/s3_v4.4.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   's3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 's3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 's3/lib/index' {
  declare module.exports: any;
}

declare module 's3/lib/multipart_etag' {
  declare module.exports: any;
}

// Filename aliases
declare module 's3/lib/index.js' {
  declare module.exports: $Exports<'s3/lib/index'>;
}
declare module 's3/lib/multipart_etag.js' {
  declare module.exports: $Exports<'s3/lib/multipart_etag'>;
}
