// flow-typed signature: 2092c15b2e9e984a135ba5eafab5d20a
// flow-typed version: <<STUB>>/tomlify-j0.4_v3.0.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tomlify-j0.4'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tomlify-j0.4' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tomlify-j0.4/dist/tomlify.min' {
  declare module.exports: any;
}

declare module 'tomlify-j0.4/tomlify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tomlify-j0.4/dist/tomlify.min.js' {
  declare module.exports: $Exports<'tomlify-j0.4/dist/tomlify.min'>;
}
declare module 'tomlify-j0.4/tomlify.js' {
  declare module.exports: $Exports<'tomlify-j0.4/tomlify'>;
}
